# to deploy manually use `gcloud app deploy`
# dev env is default service on google app engine

service: fe-dev
# for stage fe-stage
# for prod fe-fe-prod

runtime: nodejs16
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
