# gcloud app deploy app-dev.yaml

steps:
  - name: node:16.20.1
    entrypoint: yarn
    args: ['install']
  - name: node:16.20.1
    entrypoint: yarn
    args: ['run', 'create-env']
    env:
      - 'VITE_APPLICATION_ENV=${_VITE_APPLICATION_ENV}'
      - 'VITE_ARCANA_AUTH_CLIENT_KEY=${_VITE_ARCANA_AUTH_CLIENT_KEY}'
      - 'VITE_MORALIS_API_KEY=${_VITE_MORALIS_API_KEY}'
      - 'VITE_UD_CLIENT_KEY=${_VITE_UD_CLIENT_KEY}'
      - 'VITE_AMPLITUDE_API_KEY=${_VITE_AMPLITUDE_API_KEY}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
