# to deploy manually use `gcloud app deploy --appyaml=cloudbuild-dev.yaml`
# dev env is default service on google app engine

service: default
runtime: nodejs16
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
env_variables:
  MY_VAR: 'my value'
