# gcloud app deploy app-dev.yaml

service: ns-fe-dev
runtime: nodejs16
steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ['install']
  - name: node:10.15.1
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'VITE_APPLICATION_ENV=${_VITE_APPLICATION_ENV}'
      - 'VITE_ARCANA_AUTH_CLIENT_KEY=${_VITE_ARCANA_AUTH_CLIENT_KEY}'
      - 'VITE_MORALIS_API_KEY=${_VITE_MORALIS_API_KEY}'
      - 'VITE_UD_CLIENT_KEY=${_VITE_UD_CLIENT_KEY}'
      - 'VITE_AMPLITUDE_API_KEY=${_VITE_AMPLITUDE_API_KEY}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
